dependency:
  files:
    - pom.xml
  licenses:
    - name: com.fasterxml.jackson.datatype
      license: Apache-2.0
    - name: com.fasterxml.jackson.datatype:jackson-datatype-jdk8
      license: Apache-2.0
    - name: com.fasterxml.jackson.datatype:jackson-datatype-jsr310
      license: Apache-2.0
    - name: com.fasterxml.jackson.module:jackson-module-parameter-names
      license: Apache-2.0
    - name: org.keycloak:keycloak-spring-boot-starter
      license: Apache-2.0
    - name: org.keycloak:spring-boot-container-bundle
      license: Apache-2.0
    - name: org.slf4j:jul-to-slf4j
      license: MIT
    - name: org.slf4j:slf4j-api 
      license: MIT
