dependency:
  files:
    - pom.xml
  licenses:
    - name: com.fasterxml.jackson.datatype
      license: Apache-2.0
    - name: com.fasterxml.jackson.datatype:jackson-datatype-jdk8
      license: Apache-2.0
    - name: com.fasterxml.jackson.datatype:jackson-datatype-jsr310
      license: Apache-2.0
