language: java
cache:
  directories:
    - $HOME/.m2
before_cache:
  - rm -f $HOME/.m2/settings.xml

script:
  - mvn verify checkstyle:check com.github.spotbugs:spotbugs-maven-plugin:check
  - echo "<settings><servers><server><id>github</id><username>"$GITHUB_USER"</username><password>"$GITHUB_TOKEN"</password></server></servers></settings>" > ~/.m2/settings.xml

jdk:
  - openjdk8
  - openjdk10
  - openjdk11

deploy:
  provider: script
  script: mvn deploy
  on:
    branch: master
    jdk: openjdk8
