language: java
cache:
  directories:
  - $HOME/.m2

script: 
  - mvn verify
 
jdk:
  - openjdk8
  - openjdk10
  - openjdk11

deploy:
  provider: github maven package registry
  registry: https://maven.pkg.github.com/
  api_key: $GITHUB_TOKEN
  edge:
    branch: Support_18292_configure_project_to_deploy_to_github_packages
  skip_cleanup: true
  keep_history: true
  on:
    branch: Support_18292_configure_project_to_deploy_to_github_packages
    repo: AAFC-BICoE/dina-base-api
