language: java
cache:
  directories:
    - $HOME/.m2/repository #Cache one level down from .m2/ to avoid caching the GITHUB_TOKEN

script:
  - mvn verify checkstyle:check com.github.spotbugs:spotbugs-maven-plugin:check
  - echo "<settings><servers><server><id>bintray-aafc-bice-BICoE</id><username>"$BINTRAY_USER"</username><password>"$BINTRAY_API"</password></server></servers></settings>" > ~/.m2/settings.xml

jdk:
  - openjdk11
  - openjdk12
  - openjdk13

deploy:
  - provider: script
    script: mvn deploy
    on:
      branch: master
      jdk: openjdk8
  - provider: pages
    github_token: $GITHUB_TOKEN
    local_dir: target/generated-docs
    keep_history: true
    on:
      branch: master
      jdk: openjdk8
