language: java
cache:
  directories:
  - $HOME/.m2

script: 
  - mvn verify

jdk:
  - openjdk8
  - openjdk10
  - openjdk11

deploy:
  provider: script
  script: bash deployToGitHubRegistry.sh
  on:
    branch: Support_18292_configure_project_to_deploy_to_github_packages