language: java
cache:
  directories:
  - $HOME/.m2

script:
  - mvn verify
  - echo "<settings><servers><server><id>github</id><username>AAFC-BICoE</username><password>$GITHUB_TOKEN</password></server></servers></settings>" > ~/.m2/settings.xml

jdk:
  - openjdk8
  - openjdk10
  - openjdk11

deploy:
  provider: script
  script: mvn deploy
  on:
    branch: Support_18292_configure_project_to_deploy_to_github_packages