language: java
cache:
  directories:
    - $HOME/.m2/repository #Cache one level down from .m2/ to avoid caching the GITHUB_TOKEN

script:
  - mvn verify checkstyle:check com.github.spotbugs:spotbugs-maven-plugin:check
  - echo "<settings><servers><server><id>github</id><username>"$GITHUB_USER"</username><password>"$GITHUB_TOKEN"</password></server></servers></settings>" > ~/.m2/settings.xml

jdk:
  - openjdk8
  - openjdk10
  - openjdk11

deploy:
  provider: script
  script: mvn deploy
  on:
    branch: bug_18328_change_DbBackedIntegrationTest_to_object-store_implementation
    jdk: openjdk8
