language: java
cache:
  directories:
    - $HOME/.m2/repository #Cache one level down from .m2/ to avoid caching the GITHUB_TOKEN

script:
  - mvn verify checkstyle:check com.github.spotbugs:spotbugs-maven-plugin:check
  - echo "<settings><servers><server><id>bintray-aafc-bice-BICoE</id><username>"$BINTRAY_USER"</username><password>"$BINTRAY_API"</password></server></servers></settings>" > ~/.m2/settings.xml

jdk:
  - openjdk8
  - openjdk10
  - openjdk11

deploy:
  provider: script
  script: mvn deploy
  on:
    branch: master
    jdk: openjdk8
