= Auditing

https://javers.org/[JaVers] is used to save snapshots of DTOs on create, update and delete events. 

== Setting up your Dina Repo for auditing

dina-base does not manage the database schema for auditing. The responsibility belongs to the specific module.

== Prepare your DTO

Your DTO must be prepared with specific annotations specifically @TypeName, @Id, @PropertyName.

1. Add the Javers annotations to the DTO:

* @TypeName should be added to the class for JaVers to know the type.

* @Id and @PropertyName("id") should be added to the ID field, which JaVers uses to track multiple versions of
the same entity.

* @ShallowReference should be added to relation fields (along with Crnk's @JsonApiRelation).
This prevents a problem where the referenced resource is re-audited with all fields null.

* @Value should be added to embedded objects, like other DTOs that are considered values of a parent DTO.
e.g. "AddressDto" is an embedded Value in "PersonDto", not a standalone entity.

** When a child value
is changed, the parent object should also be updated (via timestamp update). This can be done using
@PrePersist, @PreUpdate and @PreDelete annotations on the JPA Entity.

** Child values should not be audited separately, regardless of database structure.

* @DiffIgnore should be added to any fields not needed in the snapshots, like derived DTO fields.

Check out the supported annotations https://javers.org/documentation/domain-configuration/#supported-annotations[HERE] for more details on how you can configure your domain.

== Pass the Auditing service bean to your Dina repo

When the application runs with the property `dina.auditing.enabled = true`, an AuditService bean is available in the application context.

Simply pass this bean to your dina repository and auditing will be enabled for CREATE/DELETE/UPDATE operations.

== Accessing the Auditing Endpoint

When the application runs with the property `dina.auditing.enabled = true`, the audit endpoint automatically starts.

JSONAPI endpoint at /audit-snapshot , implemented by the AuditSnapshotRepository class.

* Page results using query parameters page[limit] and page[offset].
* Filter the results:
** By author: `filter[author]=authorname`
** By instance: `filter[instanceId]=metadata/0fc10c52-91b6-4a9b-be98-e3f75b9928f7`
