= Authentication

== Getting the current user

To get the current user, you can inject a DinaAuthenticatedUser into the constructor:

```java
@Named
@Log4j2
public class MyClass {

  private DinaAuthenticatedUser currentUser;

  public MyClass(DinaAuthenticatedUser currentUser) {
    this.currentUser = currentUser;
  }

  public void logCurrentUserName() {
    log.info(currentUser.getUsername());
  }

}
```

Event though 'MyClass' is an application-scoped bean, Spring injects a DinaAuthenticaedUser proxy
object that resolves to the actual request-scope DinaAuthenticatedUser bean when DinaAuthenticatedUser's
methods are called. So calling logCurrentUserName() will print the currentUser for the current API request.

== Using a dev-mode user without needing to authenticate manually

To have a 'dev' user set automatically without needing to authenticate via Keycloak token or other
manual method, set these properties:

`keycloak.enabled: false` and `dev-user.enabled: true` (must be set together).

If specific group/role is required, use the following config:

```yaml
dev-user:
  enabled: true
  groupRole :
    aafc :
      - user
    bicoe :
      - read-only
```
