= Authentication

== Getting the current user

To get the current user, you can inject a DinaAuthenticatedUser into the constructor:

```java
@Named
@Log4j2
public class MyClass {

  private DinaAuthenticatedUser currentUser;

  public MyClass(DinaAuthenticatedUser currentUser) {
    this.currentUser = currentUser;
  }

  public void logCurrentUserName() {
    log.info(currentUser.getUsername());
  }

}
```

Event though 'MyClass' is an application-scoped bean, Spring injects a DinaAuthenticaedUser proxy
object that resolves to the actual request-scope DinaAuthenticatedUser bean when DinaAuthenticatedUser's
methods are called. So calling logCurrentUserName() will print the currentUser for the current API request.

== Using a dev-mode user without needing to authenticate manually

To have a 'dev' user set automatically without needing to authenticate via Keycloak token or other
manual method, add these properties to your launch config:

* dev-user.enabled: true
* keycloak.enabled: false

== Setting up your Dina Repo for authorization

=== Overview

A dina repository can optionally take a DinaAuthorizationService implementation, which if present will be used to call a set of specific methods for CREATE/UPDATE/DELETE operations.

The DinaAuthorizationService is an interface defining the following methods:

```java
    void authorizeCreate(Object entity);

    void authorizeUpdate(Object entity);

    void authorizeDelete(Object entity);
```

Where each method is called by the dina repo for the appropriate operation on a given entity for that repo's domain.

=== Step by Step: Using a custom Dina Authorization Service

* Create your Dina Authorization Service implementation
* Pass your Dina Authorization Service to your Dina Repository

```java
  @Bean
  public DinaRepository<PersonDTO, Person> dinaRepository() {
    return new DinaRepository<PersonDTO,Person>(
      dinaDatabaseService,
      authorizationService,
    
    ....
  }
```

* Your dina repo will now use your Dina Authorization Service.

=== Using the default Group Authorization Service

When keycloak is enabled a default Group Authorization Service bean is available in the application context that can be injected into your Dina Repositories

* Pass the Group Authorization Service to your Dina Repository

```java
  @Inject
  private Optional<GroupAuthorizationService> groupAuthService;

  @Bean
  public DinaRepository<PersonDTO, Person> dinaRepository() {
    return new DinaRepository<PersonDTO,Person>(
      dinaDatabaseService,
      groupAuthService,
    
    ....
  }
```

* Run with `keycloak.enabled = true`
* Your dina repo will now use the default Group Authorization Service. See GroupAuthorizationService.java.