= Setting up your Dina Repo for authorization

== Overview

A dina repository can optionally take a DinaAuthorizationService implementation, which if present will be used to call a set of specific methods for CREATE/UPDATE/DELETE operations.

The DinaAuthorizationService is an interface defining the following methods: _authorizeCreate, authorizeUpdate, authorizeDelete_.

Where each method is called by the dina repo for the appropriate operation on a given entity for that repo's domain.

== Step by Step: Using a custom Dina Authorization Service

* Create your Dina Authorization Service implementation

[source,java]
----
@Service
@RequiredArgsConstructor
public class CustomAuthorizationService implements DinaAuthorizationService {

  @Inject
  private final Optional<DinaAuthenticatedUser> user;

  @Override
  public void authorizeCreate(Object entity) {
    if (!(user.isPresent()) || !(entity instanceof DinaEntity)) {
      return;
    }

    DinaEntity dinaEntity = (DinaEntity) entity;
    Set<String> userGroups = user.get().getGroups();

    if (CollectionUtils.isEmpty(userGroups) || dinaEntity.getGroup() == null) {
      throw new ForbiddenException("You shall not pass");
    }

    if (userGroups.stream().noneMatch(dinaEntity.getGroup()::equalsIgnoreCase)) {
      throw new ForbiddenException("You shall not pass");
    }
  }

  .....
----

* Pass your Dina Authorization Service to your Dina Repository

* Your dina repo will now use your Dina Authorization Service.

=== Using the default Group Authorization Service

When keycloak is enabled a default Group Authorization Service bean is available in the application context that can be injected into your Dina Repositories

* Pass the Group Authorization Service to your Dina Repository

[source,java]
----
  @Inject
  private Optional<GroupAuthorizationService> groupAuthService;

  @Bean
  public DinaRepository<PersonDTO, Person> dinaRepository() {
    return new DinaRepository<PersonDTO,Person>(
      dinaDatabaseService,
      groupAuthService,

    ....
  }
----

* Run with `keycloak.enabled = true`
* Your dina repo will now use the default Group Authorization Service. See GroupAuthorizationService.java.

== Returning your permissions for an object

You can have permissions for three types of operations as evaluated by the dina authorization service.

.Permissions
* create
* update
* delete

When keycloak is enabled you can send a GET request and view your permissions for an object.

Send a GET request to a resource and add the Header `include-dina-permission` to your HTTP request.

.Example Response
[source,json]
----
{
  "data": [
    {
      "id": "475c1dc4-99c0-4a56-8177-3f00e4f151e1",
      "type": "person",
      "links": {
        "self": "/api/v1/person/475c1dc4-99c0-4a56-8177-3f00e4f151e1"
      },
      "meta": {
        "permissions": [
            create,
            update,
            delete
        ],
        "warnings": null
      },
      "attributes": {
        ... // shortened
        ]
      },
      "relationships": {
        ... // shortened
      }
    }
  ],
  "meta": {
    ... // shortened
  }
}
----