= Field adapters

Field adapters allow you to provide custom mappings between fields.

We have a field in a DTO that is of type Integer that we want to map between an entity where the field is of type string.

We will need to provide a custom mapping.

== Implement a Dina Field Adapter for the field.

Example Implementation:

[source,java]
----
class CustomFieldAdapterImpl implements DinaFieldAdapter<CarDto, Car, Integer, String> {

    //No args constructor required
    public CustomFieldAdapterImpl() {
    }

    @Override
    public Integer toDTO(String s) {
      return Integer.valueOf(s);
    }

    @Override
    public String toEntity(Integer integer) {
      return Integer.toString(integer);
    }

    @Override
    public Consumer<String> entityApplyMethod(Car dtoRef) {
      return dtoRef::setCustomField;
    }

    @Override
    public Consumer<Integer> dtoApplyMethod(CarDto entityRef) {
      return entityRef::setCustomField;
    }
  }
----

The `toDTO` and `toEntity` methods provide the logic to convert the field value from DTO to Entity and vice versa. The `entityApplyMethod` and `dtoApplyMethod` methods allow you to supply the method that will apply the converted values to the appropriate field. In this example we use the base Setters as the methods that will apply the converted values.

== Annotate your field with IgnoreDinaMapping

- Mark your field in your DTO with the `IgnoreDinaMapping` annotation.

[source,java]
----
    @IgnoreDinaMapping(reason = "Custom resolved field")
    private String customField;
----

== Annotate your class with CustomFieldAdapter

- Mark your DTO with the `CustomFieldAdapter` annotation and give it the adapter you created in step one.

[source,java]
----
  @CustomFieldAdapter(adapters = CustomFieldAdapterImp.class)
  public static final class StudentDto {
----