= General Design Principles

General design principles applicable on all DINA modules.

== Layers

The targeted architecture is a based on a 3-layer architecture. Communication between layers would be done using DTOs (Data Transfer Objects) or Entities depending on the layer.

[plantuml,svg,align="center"]
----
include::layers.plantuml[]
----

=== Repository Layer
* Tightly coupled to the service and mapping layer.
* Communicates to the service layer for access to database resources but never contacts the database directly.
* Communicates to the mapping layer to process entities into DTO's and vise versa.
* Processes incoming HTTP requests for the API endpoint to send the appropriate response.
* Processing of incoming HTTP request is mostly handled automatically by the underlying Crnk framework. Crnk will process the incoming request and send it to the appropriate method while mapping the request body and parameters to the required method parameters.
* The repository layer is where most of the Crnk related processing should happen for example processing the filters of the query spec. 
* The repository layer is where mapping should take place between entities and DTO's.
* Communication to the service layer is usually done through the use of entity classes, and communication to the HTTP layer is usually done through the use of DTO's which have been mapped from their database backed entity representations.
* Each repository requires a specific database service class implementation and a mapper.

=== Service Layer
* Mainly used for database access and entity processing before CREATE/UPDATE/DELETE operations.
* Has methods that can be over ridden to inject business logic to process entities before CREATE/UPDATE/DELETE operations. Most notably the `preCreate preUpdate preDelete` methods.

.preCreate auto generate UUID on create
[source,java]
----
    @Override
    protected void preCreate(Person entity) {
      entity.setUuid(UUID.randomUUID());
    }
----

* Should be used for typical pre-persist, pre-update, and pre-delete operations when they can be applied.

=== Mapping Layer
* Responsible for mapping entities to their DTO equivalents and vice versa.
* These are simple field to field bean mapping operations that can be extended to apply custom field mappings for specific fields.
* Mappers should have mechanisms in place to allow for the exclusion of fields and/or relationships during the mapping process.
* Mappers should not communicate with the service layer to map relations directly.

== Resource Id as UUID
All database identifiers should be numerical based since it`s efficient and easier to manage at the database level. Even if there is no issue about leaking business information we will still expose UUID instead of the database key in the API. This will give us more flexibility at the database level while reducing potential issues with API users iterating over ids or using a wrong set of ids. Based on the “Inter-module foreign key” module, UUID’s will help detect wrong linkages by making it almost impossible to reuse a key of the wrong resource. Numerical id’s can be reused in different resources (even if this can be solved by using a global sequence) while UUID are more likely to be unique across the system.

== Inter-module foreign keys
To reduce referential integrity violation while maintaining the system simplicity and easy of use, the following rules should be applied:

* Soft-delete only: entities should never be completely deleted. Instead, they should have a deletedDate property setting the date of deletion. Such entity should return a 410 Gone instead of a 404, with a body indicating how to access the deleted entity (e.g. sample/cf71a71e-2176-4d6f-9f17-a4c4f3dd104e?deleted=true)
* Each modules should have an asynchronous job to report all external foreign key usage.
* There is no enforcement on insert/update since services can not talk to another service to check if the key actually exists

== Inter-module communication

All inter-module communications are coordinated by the client (e.g. the integrated UI). In order to reduce coupling and increase maintainability, no modules are allowed to talk to each other directly. In the event where 2 modules shall communicate, a new “proxy” module should be created to orchestrate the communication but it should be avoided.
No distributed transactions mechanism will be implemented. Possible inconsistencies due to a “transaction” that would require 2 modules, where 1 is temporary down, are acceptable as long as there is a way to report them.

Pros:
* A module will not be able to take another one down
* Simpler module deployment and maintenance

Cons:
* No referential integrity enforcement on external foreign keys
* No direct feedback to the API user on a possible bad linking between 2 services
