= One to Many Associations

There is some common functionality the currently needs to be run to resolve associations between child and parent resources.

This documentation will provide the current strategies used in dina base to help resolve child/parent associations.

Basic information around Hibernates requirements for Bi directional associations : https://vladmihalcea.com/the-best-way-to-map-a-onetomany-association-with-jpa-and-hibernate/[Article]

== Using the OneToManyDinaService

The simplest way would be to extend the OneToManyDinaService. After extending a OneToManyDinaService, the constructor will require you to supply a list of OneToManyFieldHandler as shown in the example service below.

[source,java]
----
    @Service
    public static class ParentService extends OneToManyDinaService<Parent> {

      public ParentService(
        @NonNull BaseDAO baseDAO,
        @NonNull SmartValidator validator
      ) {
        super(baseDAO, validator,
          List.of(
            new OneToManyFieldHandler<>(
              Child.class, // Class type of the child resource
              child -> child::setParent, // Method to apply the parent to the child
              Parent::getChildren, // Method to supply the children from the parent
              "parent", // field name of the parent on the child class
              child -> child.setParent(null), // Method to handle orphaned children of the parent resource
              (child, child2) -> child.getUuid().equals(child2.getUuid())))); // Method to determine two children represent the same resource
      }

      @Override
      protected void preCreate(Parent entity) {
        entity.setUuid(UUID.randomUUID());
      }

    }
----

If you need to perform any actions before the OneToManyDinaService runs the handlers, you can override 3 designated methods which will be run before the handlers.

[source,java]
----
  public void preHandleCreate(E entity) {
  }

  public void preHandleUpdate(E entity) {
  }

  public void preHandleDelete(E entity) {
  }
----

== Using OneToManyFieldHandler directly

OneToManyFieldHandlers can handle parent/child associations for a single field.

If you cannot extend the OneToManyDinaService or need to handle associations outside of this class, you can always use the OneToManyFieldHandlers directly.

After creating the OneToManyFieldHandler for a single field, 3 methods will be provided to allow you to resolve associations for common create/update/delete operations.

[source,java]
----
  public void onCreate(P parent)

  public void onUpdate(P parent, DinaService<?> dinaService)

  public void onDelete(P parent)
----
