= Test Support
`dina-test-support` package is a set of utility classes to simplify testing in the different DINA Modules.

== Running integration tests against a Postgres Docker container using PostgresTestContainerInitializer

Initializes a Postgres TestContainer if the "embedded.postgresql.enabled" property is true.

Use this initializer in integration tests by adding this annotation to your test class:

```
@ContextConfiguration(initializers = { PostgresTestContainerInitializer.class })
```

You need to have the correct Spring launch properties set when running tests to enable the Postgres container:

```
embedded.postgresql:
  enabled: true
  init-script-file: create-test-users.sql
  database: object_store_test
```

== OpenAPI3Assertions

`OpenAPI3Assertions` contains methods to run assertions between an API response and an OpenAPI 3 specification's schema. Some of the Open API 3 files could be
stored on remote servers potentially making the tests unstable. When `OpenAPI3Assertions.assertRemoteSchema` is used, the system propety `testing.skip-remote-schema-validation` can be used to temporarly skip the validation of an API response against a remote schema.