name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1

      - name: Setup legacy dependencies
        run: |
          mvn install:install-file -Dfile=legacy-libs/crnk/crnk-client/crnk-client-3.2.20200419165537.jar -DgroupId=io.crnk -DartifactId=crnk-client -Dversion=3.2.20200419165537 -Dpackaging=jar
          mvn install:install-file -Dfile=legacy-libs/crnk/crnk-data-jpa/crnk-data-jpa-3.2.20200419165537.jar -DgroupId=io.crnk -DartifactId=crnk-data-jpa -Dversion=3.2.20200419165537 -Dpackaging=jar
          mvn install:install-file -Dfile=legacy-libs/crnk/crnk-operations/crnk-operations-3.2.20200419165537.jar -DgroupId=io.crnk -DartifactId=crnk-operations -Dversion=3.2.20200419165537 -Dpackaging=jar
          mvn install:install-file -Dfile=legacy-libs/crnk/crnk-setup-spring-boot2/crnk-setup-spring-boot2-3.2.20200419165537.jar -DgroupId=io.crnk -DartifactId=crnk-setup-spring-boot2 -Dversion=3.2.20200419165537 -Dpackaging=jar
        
      - name: Build with Maven
        run: mvn -B -q install

      - name: Run Checkstyle
        run: mvn -q checkstyle:check

      - name: Run SpotBugs
        run: mvn -q spotbugs:check

      - name: Check Test Coverage (JaCoCo)
        run: mvn -pl dina-base-api jacoco:check

      - name: Run OWASP dependency-check (only on dev)
        run: mvn org.owasp:dependency-check-maven:check
        if: ${{ github.ref == 'refs/heads/dev' }}

      - name: Set up for Maven Central deploy (master branch only)
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: actions/setup-java@v4
        with: # running setup-java again overwrites the settings.xml
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_CENTRAL_PW
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Publish to Maven Central (master branch only)
        run: mvn -DsignArtifacts=true --batch-mode javadoc:jar deploy
        if: ${{ github.ref == 'refs/heads/master' }}
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PW: ${{ secrets.MAVEN_CENTRAL_PW }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

      - name: Deploy GitHub Pages (master branch only)
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/generated-docs
