name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn install

      - name: Run Checkstyle
        run: mvn checkstyle:check

      - name: Run SpotBugs
        run: mvn spotbugs:check

      - name: Check Test Coverage (JaCoCo)
        run: mvn -pl dina-base-api jacoco:check

      - name: Run OWASP dependency-check (only on dev)
        run: mvn org.owasp:dependency-check-maven:check
        if: ${{ github.ref == 'refs/heads/dev' }}

      - name: Set up for BinTray deploy (master branch only)
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: actions/setup-java@v1
        with: # running setup-java again overwrites the settings.xml
          java-version: 11
          server-id: bintray
          server-username: BINTRAY_USERNAME
          server-password: BINTRAY_TOKEN

      - name: Publish to BinTray (master branch only)
        run: mvn deploy
        if: ${{ github.ref == 'refs/heads/master' }}
        env:
          BINTRAY_USERNAME: aafc-bice
          BINTRAY_TOKEN: ${{ secrets.BINTRAY_API_KEY }}
