name: Prepare dina-base-api release
  
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Set Version
        run: |
          mvn build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion} versions:commit
          mvn help:evaluate -Dexpression=project.version -q -DforceStdout > version.txt
      - name: Push to dev 
        run: |
          VERSION=$(cat version.txt)
          rm version.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Prepare $VERSION release"
          git push origin dev
